language: objective-c
osx_image: xcode8.1
script:
  - xcodebuild -version
  - xcodebuild -workspace wascar.xcworkspace -scheme wascar -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6,OS=10.1" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
  - bash <(curl -s https://codecov.io/bash) -cF ios  