platform :ios, '9.0'

target 'wascar' do
  use_frameworks!

	# Server
	pod 'Alamofire',		'~> 3.5'
	pod 'AlamofireImage'
	pod 'SwiftyJSON',		'~> 2.4'
	
  target 'wascarTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
